#

GNUSTEP_INSTALLATION_DIR = $(GNUSTEP_SYSTEM_ROOT)

include $(GNUSTEP_MAKEFILES)/common.make
include SCRIPT_KIT_VERSION

#
# The list of subproject directories
#
SUBPROJECTS = Library Examples

-include Makefile.preamble

include $(GNUSTEP_MAKEFILES)/aggregate.make

-include Makefile.postamble
