include $(GNUSTEP_SYSTEM_ROOT)/Makefiles/common.make
include SCRIPT_KIT_VERSION
#
# The list of subproject directories
#
SUBPROJECTS = Library Examples

-include Makefile.preamble

include $(GNUSTEP_SYSTEM_ROOT)/Makefiles/aggregate.make

-include Makefile.postamble
