
GNUSTEP_MAKEFILES = $(GNUSTEP_SYSTEM_ROOT)/Makefiles

include $(GNUSTEP_MAKEFILES)/common.make

# The application to be compiled
DOCUMENT_NAME = gstep_guile

# The texinfo source files to be used
gstep_guile_TEXI_FILES = gstep_guile

-include Makefile.preamble

-include GNUmakefile.local

include $(GNUSTEP_MAKEFILES)/documentation.make

-include Makefile.postamble
