
include $(GNUSTEP_SYSTEM_ROOT)/Makefiles/common.make

# The application to be compiled
DOCUMENT_NAME = gstep_guile

# The texinfo source files to be used
gstep_guile_TEXI_FILES = gstep_guile

-include Makefile.preamble

include $(GNUSTEP_SYSTEM_ROOT)/Makefiles/documentation.make

-include Makefile.postamble
